### ISSUE TITLE
Unhygienic client side names

### ISSUE THREAD

**Issue by dhil** [links-lang/links#1086]
The following program crashes on the client when the user clicks the button.
```links
alien javascript "" stringifyB64 : (Int) -> Int;

fun mainPage(_) {
  page
    <#>
      <button l:onclick="{println(intToString(stringifyB64(2) + 2))}">Click me</button>
    </#>
}

fun main() {
  addRoute("/", mainPage);
  servePages()
}

main()
```

The reason being that `stringifyB64 : (a) -> String` is defined in `jslib.js`. It should have a safe name.

Curiously, the error indicates another issue.
```
jslib.js:1530 Uncaught TypeError: LINKS.b64encode is not a function
    at stringifyB64 (jslib.js:1530:47)
    at (index):3291:24
    at _yield (jslib.js:3673:12)
    at _fun__g138_2342 ((index):3291:3)
    at _2342 ((index):413:40)
    at jslib.js:1849:18
    at _cont (jslib.js:2615:38)
    at jslib.js:2624:9
    at HTMLButtonElement.<anonymous> (jslib.js:1509:15)
```
The implementation of `stringifyB64` references a function that is not present `jslib`. So, we can quite possibly just get rid of `stringifyB64` altogether.

**Comment by dhil** [comment]
This is mostly resolved by #1087. However, there is a related unresolved issue: make alien names hygienic. I suppose for now we can stick to "it is an error to use a name that is used by the runtime system" approach.
