### ISSUE TITLE
Add missing modules test file

### ISSUE THREAD

**Issue by jgbm** [links-lang/links#58]

**Comment by SimonJF** [comment]
@dhil which is the file that was missing? modules.tests and the modules directory seem to be added. I checked out a clean version of sessions, and (modules) tests passed all fine:

```
[simon@guadeloupe links]$ ./run-tests 
tests/annotations.tests
tests/bindings.tests
1 failure
tests/booleans.tests
tests/collections.tests
1 failure
tests/conditionals.tests
tests/continuations.tests
1 failure
tests/database.tests
tests/functions.tests
tests/lexing.tests
tests/library.tests
tests/messages.tests
tests/modules.tests
tests/numbers.tests
tests/patterns.tests
3 failures
tests/polymorphism.tests
tests/records.tests
tests/regex.tests
tests/sessions.tests
tests/strings.tests
tests/tuples.tests
tests/variants.tests
tests/xml.tests
6 total failures
307 total successes
```

**Comment by dhil** [comment]
It would appear to be the test "module chasing":
```
$ ./test-harness tests/modules.tests 
 SUCCESS: Modules hide inner definitions
 SUCCESS: Basic qualified binding resolution
 SUCCESS: Inner module qualified binding resolution
 SUCCESS: Open allows basic unqualified binding access
 SUCCESS: Module nesting allows partially-qualified names to be used for resolution
 SUCCESS: Open allows partially-qualified names to be used for resolution
 SUCCESS: Open still allows fully-qualified names to be used
 SUCCESS: Opened module does not shadow bindings after opening
 SUCCESS: Opened module shadows previous bindings after opening
 SUCCESS: Cyclic dependencies outlawed
Traceback (most recent call last):
  File "./test-harness", line 100, in <module>
    main()
  File "./test-harness", line 96, in main
    evaluate(name, code, **opts)
  File "./test-harness", line 64, in evaluate
    proc = Popen((code, extern_args), stdout=PIPE, stderr=PIPE, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by fehrenbach** [comment]
I still get this when running `./test-harness tests/modules.tests`
```
!FAILURE: Module chasing
  error: Module chasing
      (Unexpected return code: expected `0'; got `1')
  error: Module chasing
      (Unexpected stdout: expected `"hello from c!" : String'; got `')
  error: Module chasing
      (Unexpected stderr: expected `'; got `*** Fatal error : Could not find file moduleB.links')
```

**Comment by SimonJF** [comment]
Alright, sorry about that -- seemed like a cached file obscured me seeing that message.

It was an extraordinarily irritating Python intricacy. If you get the chance, please try 4ef99a99eac95b8926bb40721604486655b00c0c?

**Comment by fehrenbach** [comment]
That seems to have done it.

**Comment by SimonJF** [comment]
\o/

Thanks for checking!

**Comment by fehrenbach** [comment]
I spoke too soon. It seems to still fail on travis: https://travis-ci.org/links-lang/links/builds/157937007
It works on my laptop though... Is this assuming python 3? Maybe I can switch to that on travis?

**Comment by SimonJF** [comment]
It seems that test-harness is not up to date on the travis branch.

**Comment by fehrenbach** [comment]
You are right. I just failed at git.
